In [7]:
text = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [8]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [9]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
len(tokenizer.word_index)


282

In [39]:
len(tokenizer.word_index)

282

In [25]:
tokenized_lst=[]
for sen in text.split('\n'):
    tokenized = tokenizer.texts_to_sequences([sen])[0]
    tokenized_lst.append(tokenized)
    #print(tokenized)



In [32]:
sequence = []
for t in tokenized_lst:
    #print(len(t))
    for i in range(0,len(t)):
        #print(t[i])
        s = t[:i+1]
        #print(s)
        sequence.append(s)

In [54]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
max_length = max([len(s) for s in sequence])
print (max_length)
padded_sequence = pad_sequences(sequence,maxlen=max_length,padding ='pre')

57


In [55]:
X = padded_sequence[:,:-1]
y = padded_sequence[:,-1]

In [ ]:
X.shape,y.shape
print(padded_sequence[:,-1])

In [57]:
from tensorflow.keras.utils import to_categorical

y_actual = to_categorical(y,num_classes=len(tokenizer.word_index)+1)

In [58]:
print(y_actual.shape)
print(y_actual[:5])

(940, 283)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [60]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Bidirectional

In [73]:
import warnings

warnings.filterwarnings('ignore')

model = Sequential()
model.add(Embedding(input_dim=283,output_dim=100,input_length=max_length-1))
model.add(Bidirectional(LSTM(64,return_sequences=True)))
model.add(Bidirectional(LSTM(64,return_sequences=False)))
model.add(Dense(283,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_12                │ ?                      │   0 (unbuilt) │
│ (Bidirectional)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_13                │ ?                      │   0 (unbuilt) │
│ (Bidirectional)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [77]:
X.shape

(940, 56)

In [66]:
model.build(input_shape=(None, X.shape[1]))
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 56, 100)        │        28,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_8 (Bidirectional) │ (None, 56, 128)        │        84,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_9 (Bidirectional) │ (None, 128)            │        98,816 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 283)            │        36,507 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 248,103 (969.15 KB)

 Trainable params: 248,103 (969.15 KB)

 Non-trainable params: 0 (0.00 B)

In [78]:
model.fit(X,y_actual,epochs=100,batch_size=90,verbose=1)

Epoch 1/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step - accuracy: 0.8940 - loss: 0.4312
Epoch 2/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - accuracy: 0.8984 - loss: 0.3809
Epoch 3/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.8828 - loss: 0.4330
Epoch 4/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step - accuracy: 0.8984 - loss: 0.3965
Epoch 5/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - accuracy: 0.8829 - loss: 0.4535
Epoch 6/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - accuracy: 0.8808 - loss: 0.4612
Epoch 7/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step - accuracy: 0.8857 - loss: 0.4190
Epoch 8/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step - accuracy: 0.8825 - loss: 0.4646
Epoch 9/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.8878 - loss: 0.4358
Epoch 10/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step - accuracy: 0.8799 - loss: 0.4355
Epoch 11/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.8774 - loss: 0.4327
Epoch 12/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step

In [97]:
import time
import numpy as np

text ="what is the course"

tokenized_text = tokenizer.texts_to_sequences([text])[0]
print(tokenized_text)

padded_tokenized_text = pad_sequences([tokenized_text],maxlen=max_length,padding ='pre')
print(padded_tokenized_text)




[11, 7, 1, 12]
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0 11  7  1 12]]


In [98]:
pos = np.argmax(model.predict(padded_tokenized_text))
print(pos)
for i in tokenizer.word_index:
    if tokenizer.word_index[i] == pos:
        print(i)
        break

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
42
fee


In [103]:
text ="what"

for i in range(10):    
    tokenized_text = tokenizer.texts_to_sequences([text])[0]
    padded_tokenized_text = pad_sequences([tokenized_text],maxlen=max_length,padding ='pre')

    pos = np.argmax(model.predict(padded_tokenized_text))

    for i in tokenizer.word_index:
        if tokenizer.word_index[i] == pos:
            print(i)
            text = text +' '+ i
            print(text)
            break

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
is
what is
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
the
what is the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
criteria
what is the criteria
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
to
what is the criteria to
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
get
what is the criteria to get
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
the
what is the criteria to get the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
certificate
what is the criteria to get the certificate
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
form
what is the criteria to get the certificate form
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
doubts
what is the criteria to get the certificate form doubts
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
doubts
what is the criteria to get the certificate form doubts doubts
