In [22]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [23]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token = '<unk>')
tokenizer.fit_on_texts(docs)

In [24]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

In [25]:
sequence = tokenizer.texts_to_sequences(docs)
from keras.utils import pad_sequences

seq = pad_sequences(sequence,padding ='post')
seq

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [30]:
len(tokenizer.word_index) + 1

19

In [35]:
seq[0]

array([10,  2,  0,  0,  0], dtype=int32)

In [34]:
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding
model1 = Sequential()
model1.add(Embedding(19,output_dim=2,input_length=5))
model1.build(input_shape=(None, 5))
model1.summary()
model1.compile('adam','accuracy')

single = seq[0]                  # shape (timesteps,)
single_input = np.expand_dims(single.astype('int32'), axis=0)  # shape (1, timesteps)

pred = model1.predict(single_input)
print(pred)


Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 5, 2)           │            38 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 38 (152.00 B)

 Trainable params: 38 (152.00 B)

 Non-trainable params: 0 (0.00 B)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
[[[-0.00781216 -0.01192696]
  [ 0.04704646 -0.00388991]
  [ 0.04941193 -0.04172568]
  [ 0.04941193 -0.04172568]
  [ 0.04941193 -0.04172568]]]


In [8]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

(X_train,y_train), (X_test,y_test) = imdb.load_data()

In [9]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [10]:
model = Sequential()
model.add(SimpleRNN(32,input_shape =(50,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))
model.summary()

c:\work_repo\AI_ML_DS_GenAI_Portfolio\.myvenv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics =['accuracy'])
model.fit(X_train,y_train,epochs =5,validation_data =(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.5014 - loss: 0.6956 - val_accuracy: 0.5068 - val_loss: 0.6937
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.5069 - loss: 0.6929 - val_accuracy: 0.5034 - val_loss: 0.6949
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5108 - loss: 0.6926 - val_accuracy: 0.5018 - val_loss: 0.6943
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.5084 - loss: 0.6929 - val_accuracy: 0.5041 - val_loss: 0.6934
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5037 - loss: 0.6928 - val_accuracy: 0.5011 - val_loss: 0.6942


In [14]:
X_train[100], y_train[100]

(array([   21,    69,     8,   401, 22239,     4,   481,    88,    61,
         4731,   238,    28,    32,    11,    32,    14,     9,     6,
          545,  1332,   766,     5,   203,    73,    28,    43,    77,
          317,    11,     4, 22228,   953,   270,    17,     6,  3616,
           13,   545,   386,    25,    92,  1142,   129,   278,    23,
           14,   241,    46,     7,   158], dtype=int32),
 np.int64(0))

In [20]:
X_train[100].ndim
sample = X_train[100]
print(sample.shape[0])
input_sample = sample.reshape(1,sample.shape[0],1)

50


In [21]:
model.predict(input_sample)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step


array([[0.511642]], dtype=float32)

In [36]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [37]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [39]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)
X_train.shape

(25000, 50)

In [45]:
vocab_size = int(max(X_train.max(), X_test.max())) + 1
print("vocab_size needed:", vocab_size)

vocab_size needed: 88586


In [46]:
model = Sequential()
model.add(Embedding(88586, 2,input_length =50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))
model.build(input_shape=(None, 50))
model.summary()

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_12 (Embedding)        │ (None, 50, 2)          │       177,172 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_4 (SimpleRNN)        │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 178,325 (696.58 KB)

 Trainable params: 178,325 (696.58 KB)

 Non-trainable params: 0 (0.00 B)

In [47]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - acc: 0.6269 - loss: 0.6131 - val_acc: 0.7910 - val_loss: 0.4563
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - acc: 0.8400 - loss: 0.3721 - val_acc: 0.8009 - val_loss: 0.4315
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - acc: 0.9001 - loss: 0.2564 - val_acc: 0.7882 - val_loss: 0.4539
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - acc: 0.9340 - loss: 0.1812 - val_acc: 0.7909 - val_loss: 0.5053
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - acc: 0.9552 - loss: 0.1299 - val_acc: 0.7913 - val_loss: 0.5370


In [50]:
sample = X_test[0]
sample_input = sample.reshape(1,sample.shape[0],1)
model.predict(sample_input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[0.71325505]], dtype=float32)

In [52]:
sample.shape[0]

50

In [54]:
X_test[0].shape

(50,)